# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import repository.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('totalmarks', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('questionpaper', models.FileField(upload_to=repository.models.set_questionpapername)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to=repository.models.set_profilepicturename)),
                ('bloodgroup', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000, unique=True)),
                ('module', models.IntegerField()),
                ('part', models.CharField(max_length=10)),
                ('co', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('exam', models.ManyToManyField(to='repository.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('resourcefile', models.FileField(upload_to=repository.models.set_filename)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('credit', models.CharField(max_length=5)),
                ('course', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=5000)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Department')),
                ('staff', models.ManyToManyField(related_name='teachingsubjects', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='subscribedsubjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Subject'),
        ),
        migrations.AddField(
            model_name='resource',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Subject'),
        ),
    ]
