# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 6, 16, 21, 1, 253104)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 6, 16, 21, 8, 283089)),
            preserve_default=False,
        ),
    ]
