# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0025_auto_20151009_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='co',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(default='Knowledge', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
