before_script: 
  - "apt-get update -qq && apt-get install -y -qq python-pip python-dev"
  - "pip install cffi"
  - "pip install -r requirements.txt"
test:
  script: 
    - "coverage run --source='.' manage.py test repository -v 2"
