language: python
python:
    - "2.7"
cache: pip
env:
  - DJANGO_VERSION=1.7.9
install:
  - "pip install -r requirements.txt"
  - "pip install codecov"
before_script:
  - "python manage.py makemigrations"
  - "python manage.py migrate"
script: 
    - "coverage run --source='.' manage.py test repository -v 2"
after_success:
  - codecov
