language: python
python:
    - "2.7"
env:
  - DJANGO_VERSION=1.7.9
install: "pip install -r requirements.txt"
script: 
    - "coverage run --source='.' manage.py test repository -v 2"
before_install:
  - pip install codecov
after_install:
  - python manage.py makemigrations
  - python manage.py migrate
after_success:
  - codecov
